name: default
channels:
    - conda-forge
    - gurobi
dependencies:
    - python=3.7
    - numpy=1.17.2
    - pandas=0.25.1
    - matplotlib=3.1.0
    - seaborn=0.9.0
    - python-ternary=1.0.6
    - jinja2=2.10.1
    - gurobi=9.0.0
    - pip=19.0.3
    - pip:
        - git+git://github.com/calliope-project/calliope.git@bcb56107bf3664c7ba38c6d2eca7bb72e393a2a5 # FIXME install development version. Remove after release of 0.6.5
